export const AppModules = [
  {
    route: '/app/tabs/dashboard',
    color: 'primary',
    icon: 'people-outline',
    id: 'Dashboard',
    name: 'Dashboard',
    title: 'Dashboard',
    hideInDashboard: true,
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/apartments',
    color: 'medium',
    icon: 'business-outline',
    id: 'Apartments',
    name: 'Apartments',
    title: 'Apartments',
    hideInDashboard: true,
  },
  {
    route: '/app/tabs/wings',
    color: 'dark',
    icon: 'grid-outline',
    id: 'Wings',
    name: 'Wings',
    title: 'Wings',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/flats',
    color: 'primary',
    icon: 'scan-circle-outline',
    id: 'Flat',
    name: 'Flats',
    title: 'Flats',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/members',
    color: 'tertiary',
    icon: 'person-add-outline',
    id: 'Members',
    name: 'Members',
    title: 'Members',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/owners',
    color: 'primary',
    icon: 'people-outline',
    id: 'Owners',
    name: 'Owners',
    title: 'Owners',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/accounts',
    color: 'secondary',
    icon: 'newspaper-outline',
    id: 'Accounts',
    name: 'Accounts',
    title: 'Accounts',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/visitors',
    color: 'tertiary',
    icon: 'people-circle-outline',
    id: 'Visitors',
    name: 'Visitors',
    title: 'Visitors',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/notices',
    color: 'success',
    icon: 'alert-circle-outline',
    id: 'Notices',
    name: 'Notices',
    title: 'Notices',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/events',
    color: 'warning',
    icon: 'calendar-number-outline',
    id: 'Events',
    name: 'Events',
    title: 'Events',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/rules',
    color: 'danger',
    icon: 'checkmark-done-outline',
    id: 'Rules',
    name: 'Rules',
    title: 'Rules',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/vehicles',
    color: 'secondary',
    icon: 'car-sport-outline',
    id: 'Vehicles',
    name: 'Vehicles',
    title: 'Vehicles',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/staff',
    color: 'success',
    icon: 'person-circle-outline',
    id: 'Staff',
    name: 'Staff',
    title: 'Staff',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/notifications',
    color: 'warning',
    icon: 'checkbox-outline',
    id: 'My Notifications',
    name: 'My Notifications',
    title: 'My Notifications',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/inventory',
    color: 'danger',
    icon: 'list-outline',
    id: 'Inventory',
    name: 'Inventory',
    title: 'Inventory',
    hideInSideMenu: true,
  },
  {
    route: '/app/tabs/tenants',
    color: 'medium',
    icon: 'accessibility-outline',
    id: 'Tenants',
    name: 'Tenants',
    title: 'Tenants',
    hideInSideMenu: true,
  },
  {
    route: '/account',
    color: 'medium',
    icon: 'person-circle-outline',
    id: 'Tenants',
    name: 'User Profile',
    title: 'User Profile',
    hideInDashboard: true,
    hideInSideMenu: true,
  },
]
