export const AppModules = [
  {
    route: "/app/tabs/dashboard",
    color: "primary",
    icon: "people-outline",
    id: "Dashboard",
    profilePic: "/assets/img/owner.png",
    name: "Dashboard",
    title: "Dashboard",
  },
  {
    route: "/app/tabs/apartments",
    color: "medium",
    icon: "business-outline",
    id: "Apartments",
    profilePic: "/assets/img/wings.png",
    name: "Apartments",
    title: "Apartments",
  },
  {
    route: "/app/tabs/wings",
    color: "dark",
    icon: "grid-outline",
    id: "Wings",
    profilePic: "/assets/img/wings.png",
    name: "Wings",
    title: "Wings",
  },
  {
    route: "/app/tabs/flat",
    color: "primary",
    icon: "scan-circle-outline",
    id: "Flat",
    profilePic: "/assets/img/flat.png",
    name: "Flat",
    title: "Flat",
  },
  {
    route: "/app/tabs/owners",
    color: "primary",
    icon: "people-outline",
    id: "Owners",
    profilePic: "/assets/img/owner.png",
    name: "Owners",
    title: "Owners",
  },
  {
    route: "/app/tabs/accounts",
    color: "secondary",
    icon: "newspaper-outline",
    id: "Accounts",
    profilePic: "/assets/img/accounts.png",
    name: "Accounts",
    title: "Accounts",
  },
  {
    route: "/app/tabs/visitors",
    color: "tertiary",
    icon: "people-circle-outline",
    id: "Visitors",
    profilePic: "/assets/img/visitors.png",
    name: "Visitors",
    title: "Visitors",
  },
  {
    route: "/app/tabs/notices",
    color: "success",
    icon: "alert-circle-outline",
    id: "Notices",
    profilePic: "/assets/img/notices.png",
    name: "Notices",
    title: "Notices",
  },
  {
    route: "/app/tabs/events",
    color: "warning",
    icon: "calendar-number-outline",
    id: "Events",
    profilePic: "/assets/img/events.png",
    name: "Events",
    title: "Events",
  },
  {
    route: "/app/tabs/rules",
    color: "danger",
    icon: "checkmark-done-outline",
    id: "Rules",
    profilePic: "/assets/img/rules.png",
    name: "Rules",
    title: "Rules",
  },
  {
    route: "/app/tabs/vehicles",
    color: "secondary",
    icon: "car-sport-outline",
    id: "Vehicles",
    profilePic: "/assets/img/flat.png",
    name: "Vehicles",
    title: "Vehicles",
  },
  {
    route: "/app/tabs/members",
    color: "tertiary",
    icon: "person-add-outline",
    id: "Members",
    profilePic: "/assets/img/flat.png",
    name: "Members",
    title: "Members",
  },
  {
    route: "/app/tabs/staff",
    color: "success",
    icon: "person-circle-outline",
    id: "Staff",
    profilePic: "/assets/img/flat.png",
    name: "Staff",
    title: "Staff",
  },
  {
    route: "/app/tabs/notifications",
    color: "warning",
    icon: "checkbox-outline",
    id: "My Notifications",
    profilePic: "/assets/img/flat.png",
    name: "My Notifications",
    title: "My Notifications",
  },
  {
    route: "/app/tabs/inventory",
    color: "danger",
    icon: "list-outline",
    id: "Inventory",
    profilePic: "/assets/img/flat.png",
    name: "Inventory",
    title: "Inventory",
  },
  {
    route: "/app/tabs/tenants",
    color: "medium",
    icon: "accessibility-outline",
    id: "Tenants",
    profilePic: "/assets/img/flat.png",
    name: "Tenants",
    title: "Tenants",
  },
];
